[licenses]
allow = [
    "MIT",
    "Unicode-3.0",
    "BSD-3-Clause",
    "Apache-2.0",
    "GPL-2.0-only",
    "BSL-1.0",
    "BSD-2-Clause",
    "Zlib",
    "ISC",
    "OFL-1.1",
    "Ubuntu-font-1.0"
]

[bans]
multiple-versions = "allow"